services:
    _defaults:
        public: true

    Instride\Bundle\PimcoreElementManagerBundle\Command\IndexCommand:
        arguments:
          - '@Instride\Bundle\PimcoreElementManagerBundle\Metadata\DuplicatesIndex\MetadataRegistry'
          - '@Instride\Bundle\PimcoreElementManagerBundle\DuplicateIndex\DuplicatesIndexWorker'
          - '@Instride\Bundle\PimcoreElementManagerBundle\DuplicateIndex\DuplicateFinder'
          - '@event_dispatcher'
        tags:
          - { name: console.command, command: 'pimcore-element-manager:duplicate-index' }
