parameters:
    duplication_checker.cache.prefix: ''
    duplication_checker.cache.file: '%kernel.cache_dir%/duplication.php'

services:
    duplication_checker.cache:
        parent: cache.system
        tags:
            - { name: cache.pool }

    duplication_checker.validator:
        class: Symfony\Component\Validator\Validator\ValidatorInterface
        public: false
        factory: ['@duplication_checker.builder', 'getValidator']

    duplication_checker.builder:
        class: Symfony\Component\Validator\ValidatorBuilder
        public: false
        autowire: false
        autoconfigure: false
        calls:
            -   method: setConstraintValidatorFactory
                arguments:
                    - '@duplication_checker.validator_factory'

    duplication_checker.validator_factory:
        class: Instride\Bundle\PimcoreElementManagerBundle\DuplicateChecker\ContainerConstraintValidatorFactory
        public: false
        arguments:
            - '@service_container'

    duplication_checker.mapping.cache_warmer:
        class: Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer
        public: false
        arguments:
            - '@duplication_checker.builder'
            - '%duplication_checker.cache.file%'
            - '@duplication_checker.cache'
        tags:
            - { name: kernel.cache_warmer }

    duplication_checker.mapping.cache.adapter:
        class: Symfony\Component\Cache\Adapter\PhpArrayAdapter
        public: false
        factory: ['Symfony\Component\Cache\Adapter\PhpArrayAdapter', 'create']
        arguments:
            - '%duplication_checker.cache.file%'
            - '@duplication_checker.cache'

    Instride\Bundle\PimcoreElementManagerBundle\DuplicateChecker\DuplicateService:
        arguments:
            - '@duplication_checker.validator'

    Instride\Bundle\PimcoreElementManagerBundle\DuplicateChecker\DuplicateServiceInterface: '@Instride\Bundle\PimcoreElementManagerBundle\DuplicateChecker\DuplicateService'
