services:
    Wvision\Bundle\ElementManagerBundle\SaveManager\NamingScheme\ExpressionNamingScheme:
        arguments:
            - '@coreshop.expression_language'

    Wvision\Bundle\ElementManagerBundle\SaveManager\ValidationSaveHandler:
        arguments:
            - '@validator'

    Wvision\Bundle\ElementManagerBundle\SaveManager\DuplicationSaveHandler:
        arguments:
            - '@Wvision\Bundle\ElementManagerBundle\DuplicateChecker\DuplicateServiceInterface'

    Wvision\Bundle\ElementManagerBundle\EventListener\ObjectEventListener:
        arguments:
            - '@Wvision\Bundle\ElementManagerBundle\SaveManager\ObjectSaveManagers'
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: onPreUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: onPostUpdate }
            - { name: kernel.event_listener, event: pimcore.dataobject.preAdd, method: onPreAdd }
            - { name: kernel.event_listener, event: pimcore.dataobject.postAdd, method: onPostAdd }
            - { name: kernel.event_listener, event: pimcore.dataobject.preDelete, method: onPreDelete }
            - { name: kernel.event_listener, event: pimcore.dataobject.postDelete, method: onPostDelete }
