services:
    Wvision\Bundle\ElementManagerBundle\DuplicateIndex\DataTransformer\ContainerDataTransformerFactory:
        arguments:
            - []

    Wvision\Bundle\ElementManagerBundle\DuplicateIndex\Similarity\ContainerSimilarityCheckerFactory:
        arguments:
            - []

    Wvision\Bundle\ElementManagerBundle\DuplicateIndex\DataTransformer\DataTransformerFactoryInterface: '@Wvision\Bundle\ElementManagerBundle\DuplicateIndex\DataTransformer\ContainerDataTransformerFactory'
    Wvision\Bundle\ElementManagerBundle\DuplicateIndex\Similarity\SimilarityCheckerFactoryInterface: '@Wvision\Bundle\ElementManagerBundle\DuplicateIndex\Similarity\ContainerSimilarityCheckerFactory'

    Wvision\Bundle\ElementManagerBundle\DuplicateIndex\DuplicatesIndexWorker:
        arguments:
            - '@Wvision\Bundle\ElementManagerBundle\DuplicateIndex\DataTransformer\DataTransformerFactoryInterface'
            - '@doctrine.orm.entity_manager'
            - '@wvision_element_manager.repository.duplicate'
            - '@wvision_element_manager.repository.duplicate_object'
            - '@wvision_element_manager.factory.duplicate'
            - '@wvision_element_manager.factory.duplicate_object'

    Wvision\Bundle\ElementManagerBundle\DuplicateIndex\DuplicateFinder:
        arguments:
            - '@Wvision\Bundle\ElementManagerBundle\DuplicateIndex\Similarity\SimilarityCheckerFactoryInterface'
            - '@wvision_element_manager.repository.duplicate'
            - '@wvision_element_manager.repository.duplicate_object'
            - '@wvision_element_manager.repository.potential_duplicate'
            - '@doctrine.orm.entity_manager'
            - '@wvision_element_manager.factory.potential_duplicate'

    Wvision\Bundle\ElementManagerBundle\Metadata\DuplicatesIndex\MetadataRegistry:
        public: true
    Wvision\Bundle\ElementManagerBundle\Metadata\DuplicatesIndex\MetadataRegistryInterface:
        alias: 'Wvision\Bundle\ElementManagerBundle\Metadata\DuplicatesIndex\MetadataRegistry'
        public: true
