element_manager:
    pimcore_admin:
        js:
            startup: '/bundles/elementmanager/pimcore/js/startup.js'
            duplicate_index_item: '/bundles/elementmanager/pimcore/js/duplication_index/item.js'
            duplicate_index_panel: '/bundles/elementmanager/pimcore/js/duplication_index/panel.js'
        css:
            index: '/bundles/elementmanager/pimcore/css/elementmanager.css'
